// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL: "https://todo-b6094-default-rtdb.firebaseio.com/",
    apiKey: 'AIzaSyBFyuobqhFjUJ6BYNCPUqDCFmi2lmbveDc',
    appId: '1:620351375973:web:61a3a687091e4984b2948c',
    messagingSenderId: '620351375973',
    projectId: 'todo-b6094',
    authDomain: 'todo-b6094.firebaseapp.com',
    storageBucket: 'todo-b6094.appspot.com',
    measurementId: 'G-CGGZV2LYMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL: "https://todo-b6094-default-rtdb.firebaseio.com/",
    apiKey: 'AIzaSyCSX68kxt3YB8MSn7uk_ukUNHpIjPVtWQU',
    appId: '1:620351375973:android:8f52000394c3ad46b2948c',
    messagingSenderId: '620351375973',
    projectId: 'todo-b6094',
    storageBucket: 'todo-b6094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    databaseURL: "https://todo-b6094-default-rtdb.firebaseio.com/",
    apiKey: 'AIzaSyD5pzrhW79KzvRvXG_XlehKcRw2xEPlGfA',
    appId: '1:620351375973:ios:d1ab53f676b5df9db2948c',
    messagingSenderId: '620351375973',
    projectId: 'todo-b6094',
    storageBucket: 'todo-b6094.appspot.com',
    iosClientId:
        '620351375973-ceo0khtladsgae467eh0l6j5th6te4lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    databaseURL: "https://todo-b6094-default-rtdb.firebaseio.com/",
    apiKey: 'AIzaSyD5pzrhW79KzvRvXG_XlehKcRw2xEPlGfA',
    appId: '1:620351375973:ios:6c72aa31b19eb7b7b2948c',
    messagingSenderId: '620351375973',
    projectId: 'todo-b6094',
    storageBucket: 'todo-b6094.appspot.com',
    iosClientId:
        '620351375973-18oarrjt2dq1bu19jo0ikf6kntfh73m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
